### ISSUE TITLE
Examples doesn't seem to work with latest version of 'opentracing-php'

### ISSUE THREAD

**Issue by niborb** [jcchavezs/zipkin-php-opentracing#1]
For instance in _examples_/_backend.php_

```
use OpenTracing\Carriers\HttpHeaders;
```
does not exists anymore in 'opentracing-php'. (consequence of https://github.com/opentracing/opentracing-php/pull/38).

Could you update these examples?

**Comment by niborb** [comment]
Actually I think the 'bridge' isn't compatible at all with the latest version (1.0.0-beta2)

**Comment by jcchavezs** [comment]
@niborb thanks for coming by! Latest changes in OT are not supported. I have a working version locally that I though I pushed so I will do that on Tuesday (back to BACK). Let's keep in touch please!

**Comment by niborb** [comment]
@jcchavezs great thanks!

**Comment by niborb** [comment]
hi @jcchavezs when do you expect to push the new updates?

**Comment by niborb** [comment]
thanks for the update!
