### ISSUE TITLE
Span::log() without specified timestamp leads to an exception

### ISSUE THREAD

**Issue by ellisv** [jcchavezs/zipkin-php-opentracing#17]

**Comment by cawolf** [comment]
Hi, I see there is already an open PR for this issue. Right now, this issue is holding us back from providing Zipkin support in our opentracing bundle. Is there any chance this bug will be resolved?

**Comment by jcchavezs** [comment]
@cawolf I just updated the PR. Could please give it a look and then if green I will merge it.
