### ISSUE TITLE
Upgrade zipkin dependency

### ISSUE THREAD

**Issue by Reasno** [jcchavezs/zipkin-php-opentracing#26]
Hi there,

I am one of the contributors to Hyperf, and I believe you have tried it out already (https://github.com/hyperf-cloud/hyperf/issues/590#issue-496010006). 

Currently, I am working on a PR to introduce this package to Hyperf (https://github.com/hyperf-cloud/hyperf/pull/478#issue-311781652), but the openzipkin/zipkin-php version (1.1.1) bundled together is to low. We need a version with at least https://github.com/openzipkin/zipkin-php/issues/76#issue-334247322 fixed. Can you help me upgrade its dependency?

A pull request has been made already, and any suggestions are welcomed.

**Comment by jcchavezs** [comment]
I think version 0.1.3 does the trick: https://github.com/jcchavezs/zipkin-php-opentracing/releases/tag/0.1.3.

Thanks for collaborating!
