### ISSUE TITLE
Drop PHP 5.6 support

### ISSUE THREAD

**Issue by alexeyshockov** [jcchavezs/zipkin-php-opentracing#28]
PHP 5.6 is not supported for a year already, the same for PHP 7.0 and 7.1.

What do you think about releasing a new version with only PHP 7.2+ support?

**Comment by jcchavezs** [comment]
That sounds great to me. Actually `master` in `zipkin-php` only support `>=7.1`. Would you be up to create a branch with `zipkin-php@master` and only PHP 7.1 and then if everything works fine we can merge that.

**Comment by alexeyshockov** [comment]
OK, thanks for your feedback. I opened #30 for this change, let's move there.
