### ISSUE TITLE
Upgrade PHPUnit

### ISSUE THREAD

**Issue by jcchavezs** [jcchavezs/zipkin-php-opentracing#34]

**Comment by peter279k** [comment]
The PHPUnit `7.x` version is the latest for this repository.

If upgrading the PHPunit version to the `8.x`, i should drop `php-7.1` and let this package require `php-7.2` at least.

**Comment by jcchavezs** [comment]
I am sorry this issue wasn't clear. When I opened it, PHPUnit was an old version, I think we are good with what we have now and I don't feel like removing 7.1 from support. Thanks anyways!
