### ISSUE TITLE
PHP 8.2 Support

### ISSUE THREAD

**Issue by cdenadai** [jcchavezs/zipkin-php-opentracing#62]
On php 8.2 dinamic properties aren't allowed.

To run this package we need to add the private property scopedManager on ZipkinOpenTracing\Tracer class.

Deprecated: Creation of dynamic property ZipkinOpenTracing\Tracer::$scopeManager is deprecated in /home/denacode/projetos/partners-api/vendor/jcchavezs/zipkin-opentracing/src/ZipkinOpenTracing/Tracer.php on line 53

**Comment by cdenadai** [comment]
Solution:

Add this line on Tracer class

private ScopeManager $scopeManager;

**Comment by jcchavezs** [comment]
Up for a PR?

**Comment by cdenadai** [comment]
Hi,

I can help

Em dom., 15 de jan. de 2023 21:40, José Carlos Chávez <
***@***.***> escreveu:

> Up for a PR?
>
