### ISSUE TITLE
startSpan option 'ignore_active_span' doesn't work as expected

### ISSUE THREAD

**Issue by person-unko** [jcchavezs/zipkin-php-opentracing#66]
From the doc: _Whenever child_of reference is not passed then \OpenTracing\ScopeManager::getActive() span is used as child_of reference. In order to ignore implicit parent span pass in ignore_active_span option set to true._

This implies passing in 'ignore_active_span' => true as an option should create a new root span. Currently, while the ignore_active_span property on the created StartSpanOptions is set, it doesn't seem to be used anywhere. Creating a span with ignore_active_span set to true uses the active span regardless. If this isn't intended behaviour then I could try creating a pr.
```
public function startSpan(string $operationName, $options = []): OTSpan
    {
        if (!($options instanceof StartSpanOptions)) {
            $options = StartSpanOptions::create($options);
        }

        if (!$this->hasParentInOptions($options) && $this->getActiveSpan() !== null) { <- Check if ignore_active_span is true here?
            $parent = $this->getActiveSpan()->getContext();
            $options = $options->withParent($parent);
        }

        if (empty($options->getReferences())) {
            $span = $this->tracer->newTrace();
        } else {
            /**
             * @var ZipkinOpenTracingContext $refContext
             */
            $refContext = $options->getReferences()[0]->getSpanContext();
            $context = $refContext->getContext();

            if ($context instanceof TraceContext) {
                $span = $this->tracer->newChild($context);
            } else {
                $span = $this->tracer->nextSpan($context);
            }
        }
       ....
```

**Comment by changzee** [comment]
we need a new tag

**Comment by jcchavezs** [comment]
Done https://github.com/jcchavezs/zipkin-php-opentracing/releases/tag/2.0.4
